export enum ActionTypes {
  GET_BUDGET = '[GET_BUDGET] Get Budget',
  GET_BUDGET_SUCCESS = '[GET_BUDGET_SUCCESS] Get Budget Success',
  GET_BUDGET_FAILURE = '[GET_BUDGET_FAILURE] Get Budget Failure',

  CREATE_YEAR = '[CREATE_YEAR] Create Year',
  CREATE_YEAR_SUCCESS = '[CREATE_YEAR_SUCCESS] Create Year Success',
  CREATE_YEAR_FAILURE = '[CREATE_YEAR_FAILURE] Create Year Failure',

  CREATE_MONTH = '[CREATE_MONTH] Create Month',
  CREATE_MONTH_SUCCESS = '[CREATE_MONTH_SUCCESS] Create Month Success',
  CREATE_MONTH_FAILURE = '[CREATE_MONTH_FAILURE] Create Month Failure',

  CREATE_DAY = '[CREATE_DAY] Create Day',
  CREATE_DAY_SUCCESS = '[CREATE_DAY_SUCCESS] Create Day Success',
  CREATE_DAY_FAILURE = '[CREATE_DAY_FAILURE] Create Day Failure',

  CREATE_ITEM = '[CREATE_ITEM] Create Item',
  CREATE_ITEM_SUCCESS = '[CREATE_ITEM_SUCCESS] Create Item Success',
  CREATE_ITEM_FAILURE = '[CREATE_ITEM_FAILURE] Create Item Failure',

  DELETE_ITEM = '[DELETE_ITEM] Delete Item',
  DELETE_ITEM_SUCCESS = '[DELETE_ITEM_SUCCESS] Delete Item Success',
  DELETE_ITEM_FAILURE = '[DELETE_ITEM_FAILURE] Delete Item Failure',
}
